{% set name = "pretty_html_table" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 781c7014427f820bdb3264985edc2d9caa226e4a67d86b581e8389fbc6091a55

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - pandas
    - python

test:
  imports:
    - pretty_html_table

about:
  home: https://github.com/sbi-rviot/ph_table
  license: MIT
  license_family: MIT
  # check to see if PR: https://github.com/sbi-rviot/ph_table/pull/5 has been merged
  # so we can drop the local license in recipe
  license_file: LICENSE.txt
  summary: Make pandas dataframe looking pretty again
  doc_url: ''
  dev_url: https://github.com/sbi-rviot/ph_table

extra:
  recipe-maintainers:
    - Maarten-vd-Sande
